### ISSUE TITLE
React does not recognize the `htmlId` prop on a DOM element.

### ISSUE THREAD

**Issue by lucent1090** [TwoAbove/jsonschema-form-for-material-ui#10]
Hello,

I'm using CRA with the example code in the readme.
and I found these warnings in the console log.

Warning: Failed prop type: Invalid prop `classes` of type `function` supplied to `WithStyles(Form)`, expected `object`.
Warning: React does not recognize the `htmlId` prop on a DOM element.
Warning: Failed prop type: Material-UI: the `flat` variant will be removed in the next major release. `text` is equivalent and should be used instead.
Warning: Failed prop type: Material-UI: the `raised` variant will be removed in the next major release. `contained` is equivalent and should be used instead.

Is there any way to fix these?
Thanks a lot.

**Comment by TwoAbove** [comment]
Hey, @lucent1090 !
Yes, these errors are because material-ui has had several updates since this project started. So it's an issue with the project's code, not yours. 

In the next release I'll update all the dependencies and fix the console errors. No promises on when that will happen, but you can expect it soon

**Comment by lucent1090** [comment]
Hi @TwoAbove,
That would be great!
Thanks a lot!!

**Comment by TwoAbove** [comment]
Hey, @lucent1090 !
Updated project to 1.4.0

No errors now.
Refer to GH-11 for more info
